# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d657841e8df7c8552bdc05b883ad7f7a7b5eaad6f345a7cc9183950e23e4a6d43d8fc5d109536f52a0a0fb2b8222aa7d77b73467aff34d4ff96ee3679aea1cd0

test:
  secret_key_base: 89dca80d88371f7722191490e5c947ef3e6e15c0bbf7ddfe59b48728491d60768141dfb9bd09cddaae9e24b7388ecc98cbff0584baaf242825676a73530a5b59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
